### ISSUE TITLE
Home page health check takes down entire site

### ISSUE THREAD

**Issue by andyvanee** [octohost/octohost-cookbook#12]
f6ffd50761300339e6383734f7302a7678a0761c seems to cause some weird behaviour, and is probably related to octohost/octohost#65.

I had an issue with an improper mysql connection configuration resulting in the entire site, static assets and all, returning 500 errors. The actual page in question was timing out, but I had no idea since the only visible effect was immediate 500's across the site. Would it be bad to do `{{range service "REPLACEME" "any"}}` ([reference](https://github.com/hashicorp/consul-template#service)) just to pass that down the stack so it's visible?

Even in **successful** deployments, I've found that there are a number of seconds where the entire service returns 500 which further complicates the issue. After the deploy finishes, I can switch tabs to the octohost server and see that `/etc/nginx/containers/*.conf` has it's upstream written as `server 127.0.0.1:404;`. After a couple of seconds, the file is rewritten with the proper container/port.

Thoughts?

**Comment by darron** [comment]
Hmm. If we don't have an "else" then if there are no passing containers for a particular one, it causes nginx to fail for *all* containers - so we need something in there.

If it doesn't take out failing containers, then failing containers will still have requests routed to it - which I don't think we want.

You could define a different health check in `container-name/CUSTOM_CHECK` which wouldn't fail for that sort of thing - maybe checking a static file.

https://github.com/octohost/octohost/blob/master/bin/octo#L372-L376

Would that help?

**Comment by andyvanee** [comment]
I think I see your point. What if we were to wrap the entire file, including the upstream and server block, inside the `{{range service}}...{{end}}` block. This way we could use `range service ... "any"` but still fail if NO container was built? In my case, the container was built and running, so it could service requests - it was just failing the health check.

A custom check could help, but I don't know if it would be obvious.

**Comment by darron** [comment]
Well - you can try it all you'd like - you can customize any one of the templates - take a look here:

`/etc/nginx/templates/fairwaydev.ctmpl`

Adjust it and then run:

`octo config:consul_template_render fairwaydev` 

That will re-render it.
