### ISSUE TITLE
Digital Ocean failes on [build-essential]

### ISSUE THREAD

**Issue by singlow** [octohost/octohost-cookbook#13]
I am attempting (my first time) to use octohost via digital ocean. However it fails on `packer build -only=digitalocean template.json` because it seams that apt-update is not run and chef/apt is looking for an old version of the linux-libc-dev package. I assume that this package was updated in relation to the recent libc vulnerability. Am I doing something wrong to prevent it from getting the latest package list?

This is the error it displays:

```digitalocean: Error executing action `install` on resource 'apt_package[build-essential]'```

And further down this appears to be the root cause:

```digitalocean: STDERR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-43.72_amd64.deb  404  Not Found [IP: 91.189.91.14 80]```

**Comment by joshuacox** [comment]
weird octohost includes the apt cookbook:
https://github.com/opscode-cookbooks/apt
here:
https://github.com/octohost/octohost-cookbook/blob/master/recipes/default.rb

which certainly should run apt-get update if the timestamp of the cache is older than a day.  You can also force it with this attribute
```
['apt']['compile_time_update'] - force the default recipe to run apt-get update at compile time.
```
I will try and build a digital ocean image tomorrow on my dev setup to see if I can replicate the results.

**Comment by singlow** [comment]
Setting the compile_time_update to true did fix it. Curious - since I'm not a chef user, is there a place I should override that besides modifying apt/attributes/default.rb.

**Comment by darron** [comment]
I have built it dozens of times but I think I could include apt better. I will try too and see if I can duplicate. 

If you want, I created an automated way to build droplets:

https://obuild.octohost.io

I don't keep the key you enter (if you chose to try it) and it can be revoked after you build. 

Just an option.

**Comment by joshuacox** [comment]
Glad that helped, still not certain why that went wrong though.  As for other places, I think the chef guys have thought of every single place you could possibly want to add an attribute:

https://docs.chef.io/attributes.html

you might even just write it on a cocktail napkin stick it in a bottle and chuck it in the ocean, I'm sure the chef guys have some ruby that will retrieve it for you ;)
