### ISSUE TITLE
Failing to build AMI

### ISSUE THREAD

**Issue by girvo** [octohost/octohost-cookbook#17]
Hi all,

Following through the instructions on how to build an AMI, running `rake build_ami` gives this error:

```
Error processing token: template: tpl3:1:2: executing "tpl3" at <user `atlas_token`>: error calling user: unknown user var: atlas_token
```

Any ideas?

**Comment by darron** [comment]
Sorry about that - I think I know - taking a look right now.

**Comment by darron** [comment]
I had fixed it locally - just committed a change:

https://github.com/octohost/octohost-cookbook/commit/50aee34617d3aef66a5c2d16a0cc31686ec8735a

Should be good now.

**Comment by darron** [comment]
Let me know if that doesn't fix it @girvo - but I'm building on AWS right now with the updated JSON.

**Comment by girvo** [comment]
I'll give it a shot right now and get back to you!
