### ISSUE TITLE
invalid value "run" ?

### ISSUE THREAD

**Issue by joshuacox** [octohost/octohost-cookbook#18]
just built an octohost and got this when pushing the default harp repo at it
```
remote: Adding http://harp.65.67.51.187.xip.io
remote: invalid value "run" for flag -H: Invalid bind address format: run
remote: See 'docker --help'.
remote: invalid value "inspect" for flag -H: Invalid bind address format: inspect
remote: See 'docker --help'.
remote: invalid value "inspect" for flag -H: Invalid bind address format: inspect
remote: See 'docker --help'.
remote: Usage: octo service:set {container} {ip_address} {port} {tags}
remote: Not killing any containers.
```
I might have messed something up, but wanted to see if anyone else saw anything similar?

**Comment by darron** [comment]
If you take a look at the log in `/var/log/octohost/octohost` do you see the command it's trying to run?

**Comment by darron** [comment]
Sounds like it's trying to launch a container and it doesn't have `DOCKER_HOST` in the `/etc/default/octohost` file:

https://github.com/octohost/octohost/blob/master/bin/default#L56

**Comment by joshuacox** [comment]
ya glad I asked here before I rebuilt again, I had an old version of that I was overwriting with that indeed did not have your latest changes.  All good now, I just finished testing, thanks for the quick and always helpful response @darron
